#!/bin/tcsh

mpirun -np 4 --gm-no-shmem --gm-kill 2 /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/src/embeddedboundaries2D -f ellipse.in -pde Euler2D
cat ellipse_cpu*.dat > points.dat
cat ellipse_active_cpu*.dat > active.dat
cat ellipse_inactive_cpu*.dat > inactive.dat
cat ellipse_cells_cpu*.dat > cells.dat
cat ellipse_nodes_cpu*.dat > nodes.dat
cat ellipse_interface_component_list_cpu*.dat > components.dat
cat ellipse_interface_union_list_cpu*.dat > union.dat
rm ellipse_cpu*.dat
rm ellipse_*_cpu*.dat
