#!/bin/sh

mpirun -np 1 --gm-kill 2 /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/src/embeddedboundaries2D -f ringleb.in -pde Euler2D
cat ringleb_cpu*.dat > points.dat
cat ringleb_active_cpu*.dat > active.dat
cat ringleb_inactive_cpu*.dat > inactive.dat
cat ringleb_nodes_cpu*.dat > nodes.dat
cat ringleb_cells_cpu*.dat > cells.dat
cat ringleb_ringleb_cpu*.dat > ringleb.dat
cat ringleb_interface_component_list_cpu*.dat > components.dat
cat ringleb_interface_union_list_cpu*.dat > union.dat
rm ringleb_cpu*.dat
rm ringleb_*_cpu*.dat
