#!/bin/tcsh
#PBS -N messagepassing
#PBS -q qmaster
#PBS -l walltime=4:00:00,nodes=12:ppn=4:parallel-2G,other=night
#PBS -W group_list=xinfeng

cd /nfs/fe03/d1/cfd/xinfeng/CFFC/examples/Euler3D/shock_cube/
mpirun -np 48 --gm-no-shmem --gm-kill 2 /nfs/fe03/d1/cfd/xinfeng/CFFC/src_3D/cffc3D -f shockcube.in -pde Euler3DThermallyPerfect >& out.log 
rm messagepassing.*
cat test_cells_cpu*.dat >& ztest.dat
rm test*.dat
