#!/bin/tcsh
#
#PBS -N fp_5e6_adi_swf_ex
#PBS -q qmaster
#PBS -l walltime=8:00:00,nodes=2:ppn=4:parallel-2G,other=night
#PBS -W group_list=jai

cd /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/pdes++/examples/NavierStokes2D/flat_plate/turbulent/adiabatic/standardwallfunction/explicit/
mpirun -np 8 --gm-no-shmem --gm-kill 2 /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/src/navierstokes2D -f flatplate.in -pde NavierStokes2D >& flatplate.log
cat flatplate_cpu*.dat > points.dat
cat flatplate_cells_cpu*.dat > cells.dat
cat flatplate_flatplate_soln_cpu*.dat > flatplate.dat
cat flatplate_flatplate_skin_friction_cpu*.dat > skinfriction.dat
rm flatplate_cpu*.dat
rm flatplate_*_cpu*.dat
rm fp_5e6_adi_swf_ex.e* fp_5e6_adi_swf_ex.o*
