/* ICEMCFD.h:  Header file defining subroutines for reading 
               CFD mesh generated by ICEMCFD. */

/************************************************************************
 *                                                                      *
 *                         Written by Ming Yao Ding                     *
 *                      email: mingyao.ding@utoronto.ca                 *
 *                     Modified & written by Stefan Neata               *
 *                      email: stefan.neata@utoronto.ca                 *
 *         University of Toronto Institute for Aerospace Studies        *
 *                           Summers 2002 & 2003                        *
 *                                                                      * 
 ************************************************************************/

#ifndef _ICEMCFD_INCLUDED
#define _ICEMCFD_INCLUDED

/* Include required C++ libraries. */

#include <cstdio>
#include <iostream>
#include <fstream>
#include <cstring>

using namespace std;

/* Include ICEMCFD library header files. */

#ifdef _ICEMCFD_VERSION
#include "domain.h"
#include "topolib.h"
#include "newboco.h"
#endif

/* Include 3D hexahedral multiblock grid header file. */

#ifndef _GRID3D_HEXA_BLOCK_INCLUDED
#include "../Grid/Grid3DHexaBlock.h"
#endif //_GRID3D_HEXA_BLOCK_INCLUDED

/********************************************************
 * ICEMCFD -- ICEMCFD library name and version.         *
 ********************************************************/

// Name.
inline char *ICEMCFD_Name() {
  return("ICEMCFD");
}

// Version.
inline char *ICEMCFD_Version() {
  char *string_ptr;
#ifdef _ICEMCFD_VERSION
#ifdef _ICEMCFD_V41
  string_ptr = "ICEMCFD Version, Built using ICEMCFD Version 4.1 Libraries, ICEM CFD Engineering.";
#elif _ICEMCFD_V42
  string_ptr = "ICEMCFD Version, Built using ICEMCFD Version 4.2 Libraries, ICEM CFD Engineering.";
#elif _ICEMCFD_V43
  string_ptr = "ICEMCFD Version, Built using ICEMCFD Version 4.3 Libraries, ICEM CFD Engineering.";
#elif _ICEMCFD_V50
  string_ptr = "ICEMCFD Version, Built using ANSYS ICEM CFD Version 5.0 Libraries, ANSYS, Inc.";
#else
  string_ptr = "ICEMCFD Version, Built Incorrectly as not a proper _ICEMCFD_VERSION ";
#endif
#endif

#ifdef _NO_ICEMCFD_VERSION
  string_ptr = "No ICEMCFD Version.";
#endif
  return(string_ptr);
}

/****************************************************
 * ICEMCFD -- External Subroutines.                 *
 ****************************************************/

/****************************************************
ICEMCFD_error
****************************************************/
extern void ICEMCFD_error();

/****************************************************
ICEMCFD_get_filenames set the default file names for
the ICEMCFD boundary condition file and topology files.
The latter are required for structured mesh.
****************************************************/
extern char **ICEMCFD_get_filenames();

/****************************************************
ICEMCFD_get_boco is a function that compares the family name
of an edges to the predefined values for boundary 
conditions and returns that value.
In other words, the boundary conditions of an edges is 
set by grouping the edge into a family with one of the
following names.  BC_NONE is the default boundary type.
****************************************************/
extern int ICEMCFD_get_boco(char *file_read);

/****************************************************
ICEMCFD_get_layout determines the layout of the
multi block grid from which neighbouring information
can be determined.  The subroutine uses a recursive 
procedure to finds all of the domains and store the
layout in a 3D array.
*****************************************************/
extern void ICEMCFD_get_layout(int ***layout, int x, int y, int z,int &, int &, int &);

/********************************************************
ICEMCFD_Read reads the data in the domain files from ICEMCFD
and stores the data in a 3D hexahedral multiblock grid 
structure defined by Grid3D_Hexa_Block. The Boundary 
condtions are gathered from the toplogy and boundary 
conditions files.
********************************************************/
extern Grid3D_Hexa_Block*** ICEMCFD_Read(char **filenames, 
					 Grid3D_Hexa_Block ***Grid_ptr,
					 int *domx_buf,
					 int *domy_buf,
					 int *domz_buf);

#endif /* _ICEMCFD_INCLUDED  */
