#!/bin/tcsh
#PBS -N fans3d
#PBS -q qmaster
#PBS -l walltime=8:00:00,nodes=2:ppn=4:parallel-2G,other=night
#PBS -W group_list=xinfeng

cd /nfs/fe03/d1/cfd/xinfeng/CFFC/examples/FANS3D/channel/
mpirun -np 8 --gm-no-shmem --gm-kill 2 /nfs/fe03/d1/cfd/xinfeng/CFFC/src_3D/cffc3D -f channel.in -pde FANS3DThermallyPerfect >& out.log 
cat turbulent_channel_cells_cpu*.dat>turbulent_channel_cells.dat
rm fans3d.e*
rm fans3d.o*

