#
# $Revision: 1.7 $
# $Author: hkmoffa $
# $Date: 2006/04/30 18:06:56 $
#
#
all:
	(cd ../../examples/cxx ; make )
test:
	./runtest

clean:
	(cd ../../examples/cxx ; make clean )
	../../bin/rm_cvsignore

depends:

