#!/bin/tcsh

mpirun -np 1 --gm-no-shmem --gm-kill 2 /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/src/dusty2D -f crv7.in -pde Dusty2D
cat crv7_cpu*.dat > points.dat
cat crv7_cells_cpu*.dat > cells.dat
cat crv7_nodes_cpu*.dat > nodes.dat
cat crv7_gradients_cpu*.dat > gradients.dat
rm crv7_*cpu*.dat
