#!/bin/tcsh

mpirun -np 1 --gm-no-shmem --gm-kill 2 /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/src/embeddedboundaries2D -f crv7.in -pde NavierStokes2D
cat crv7_cpu*.dat > points.dat
cat crv7_active_cpu*.dat > active.dat
cat crv7_inactive_cpu*.dat > inactive.dat
cat crv7_cells_cpu*.dat > cells.dat
cat crv7_nodes_cpu*.dat > nodes.dat
cat crv7_status_cpu*.dat > status.dat
cat crv7_interface_component_list_cpu*.dat > components.dat
cat crv7_interface_union_list_cpu*.dat > union.dat
rm crv7_*cpu*.dat
