/* ICEMCFD.h:  Header file defining subroutines for reading 
               CFD mesh generated by ICEMCFD. */

/************************************************************************
 *                                                                      *
 *                         Written by Ming Yao Ding                     *
 *                      email: mingyao.ding@utoronto.ca                 *
 *                     Modified & written by Stefan Neata               *
 *                      email: stefan.neata@utoronto.ca                 *
 *         University of Toronto Institute for Aerospace Studies        *
 *                           Summers 2002 & 2003                        *
 *                                                                      * 
 ************************************************************************/

#ifndef _ICEMCFD_INCLUDED
#define _ICEMCFD_INCLUDED

/* Include required C++ libraries. */

#include <cstdio>
#include <iostream>
#include <fstream>
#include <cstring>

using namespace std;

/* Include ICEMCFD library header files. */

#ifdef _ICEMCFD_VERSION
#include "domain.h"
#include "topolib.h"
#include "newboco.h"
#endif

/* Include 2D quadrilateral multiblock grid header file. */

#ifndef _GRID2D_QUAD_BLOCK_INCLUDED
#include "../Grid/Grid2DQuad.h"
#endif // _GRID2D_QUAD_BLOCK_INCLUDED

/* Include 3D hexahedral multiblock grid header file. */

#ifndef _GRID3D_HEXA_BLOCK_INCLUDED
#include "../Grid/Grid3DHexa.h"
#endif //_GRID3D_HEXA_BLOCK_INCLUDED

/********************************************************
 * ICEMCFD -- ICEMCFD library name and version.         *
 ********************************************************/

// Name.
inline char *ICEMCFD_Name() {
  return("ICEMCFD");
}

// Version.
inline char *ICEMCFD_Version() {
  char *string_ptr;
#ifdef _ICEMCFD_VERSION
#ifdef _ICEMCFD_V41
  string_ptr = "ICEMCFD Version, Built using ICEMCFD Version 4.1 Libraries, ICEM CFD Engineering.";
#elif _ICEMCFD_V42
  string_ptr = "ICEMCFD Version, Built using ICEMCFD Version 4.2 Libraries, ICEM CFD Engineering.";
#elif _ICEMCFD_V43
  string_ptr = "ICEMCFD Version, Built using ICEMCFD Version 4.3 Libraries, ICEM CFD Engineering.";
#elif _ICEMCFD_V50
  string_ptr = "ICEMCFD Version, Built using ANSYS ICEM CFD Version 5.0 Libraries, ANSYS, Inc.";
#elif _ICEMCFD_V10
  string_ptr = "ICEMCFD Version, Built using ANSYS ICEM CFD Version 10 Libraries, ANSYS, Inc.";
#elif _ICEMCFD_V11
  string_ptr = "ICEMCFD Version, Built using ANSYS ICEM CFD Version 11 Libraries, ANSYS, Inc.";
#else
  string_ptr = "ICEMCFD Version, Built Incorrectly as not a proper _ICEMCFD_VERSION ";
#endif
#endif

#ifdef _NO_ICEMCFD_VERSION
  string_ptr = "No ICEMCFD Version.";
#endif
  return(string_ptr);
}

/****************************************************
 * ICEMCFD -- External Subroutines.                 *
 ****************************************************/

/****************************************************
ICEMCFD_error
****************************************************/
extern void ICEMCFD_error();

/****************************************************
ICEMCFD_get_filenames set the default file names for
the ICEMCFD boundary condition file and topology files.
The latter are required for structured mesh.
****************************************************/
extern char **ICEMCFD_get_filenames();

/****************************************************
ICEMCFD_get_boco is a function that compares the family name
of an edges to the predefined values for boundary 
conditions and returns that value.
In other words, the boundary conditions of an edges is 
set by grouping the edge into a family with one of the
following names.  BC_NONE is the default boundary type.
****************************************************/
extern int ICEMCFD_get_boco(char *file_read);

/****************************************************
ICEMCFD_get_layout determines the layout of the
multi block grid from which neighbouring information
can be determined.  The subroutine uses a recursive 
procedure to finds all of the domains and store the
layout in a 2D array.
*****************************************************/
extern void ICEMCFD_get_layout(int **layout, int x, int y, int &, int &, int &);

extern void ICEMCFD_get_layout(int ***layout, int x, int y, int z,int &, int &, int &);

/********************************************************
ICEMCFD_Read reads the data in the domain files from ICEMCFD
and stores the data in a 2D quadrilateral multiblock grid 
structure defined by the Grid2D_Quad_Block class. The Boundary 
condtions are gathered from the toplogy and boundary 
conditions files.

input scheme - import [x,y]d00,d10...dx0,d01,d11,d21...dx1...dxy

layout is a string containing the layout information for
the multi block grid. i.e. [3,2]0,1,0,3,4,2 results in a
block of the from    3-4-2   where n is null. 
                     | | |
                     n-1-n       

topomulcad is the file name for the topology information
by default the filename is "topo_mulcad_out"

boco and topo are the two boundary condition files in ICEMCFD
v4.1 by default the names are "family_boco" and "family_topo",
respectively.
********************************************************/
extern Grid2D_Quad_Block** ICEMCFD_Read(char **filenames,
                                        Grid2D_Quad_Block **Grid_ptr,
                                        int *domx_buf,
                                        int *domy_buf);

extern Grid3D_Hexa_Block*** ICEMCFD_Read(char **filenames, 
					 Grid3D_Hexa_Block ***Grid_ptr,
					 int *domx_buf,
					 int *domy_buf,
					 int *domz_buf);

#endif /* _ICEMCFD_INCLUDED  */
