#!/bin/tcsh
#
#PBS -N crv7_kw_swf
#PBS -q iqmaster
#PBS -l walltime=2:00:00,nodes=2:ppn=4:itanium-8G,other=day
#PBS -W group_list=jai

cd /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/pdes++/examples/NavierStokes2D/rocket_motor/crv7/turbulent/standard_wall_functions/
#mpirun -np 8 --gm-no-shmem --gm-kill 2 /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/src/navierstokes2D -f crv7.in -pde NavierStokes2D >& crv7.log
mpirun -np 8 --gm-no-shmem --gm-kill 2 /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/bin/navierstokes2D_i -f crv7.in -pde NavierStokes2D >& crv7.log
cat crv7_cpu*.dat > points.dat
cat crv7_cells_cpu*.dat > cells.dat
cat crv7_nodes_cpu*.dat > nodes.dat
rm crv7_*cpu*.dat
rm crv7_kw_swf.e* crv7_kw_swf.o*
