#!/bin/sh

mpirun -np 1 --gm-no-shmem --gm-kill 2 /nfs/fe01/d1/cfd/jai/CFDkit+caboodle/src/embeddedboundaries2D -f piston.in -pde NavierStokes2D
cat piston_cpu*.dat > points.dat
cat piston_active_cpu*.dat > active.dat
cat piston_inactive_cpu*.dat > inactive.dat
cat piston_cells_cpu*.dat > cells.dat
cat piston_nodes_cpu*.dat > nodes.dat
cat piston_interface_component_list_cpu*.dat > components.dat
cat piston_interface_union_list_cpu*.dat > union.dat
rm piston_cpu*.dat
rm piston_*_cpu*.dat