#!/bin/tcsh
#PBS -N Couette 
#PBS -q iserial
#PBS -l walltime=48:00:00,nodes=1:ppn=1:itanium-8G
#PBS -W group_list=xinfeng
#
cd /nfs/fe01/d1/cfd/xinfeng/THREEDCODE/THERMALLYPERFECT/pdes++/examples/NS/
/nfs/fe01/d1/cfd/xinfeng/THREEDCODE/THERMALLYPERFECT/exe/pdes++ -f test.in -pde NavierStokes3D >& put.log
rm Couette.e* Couette_NS3d.o*
